//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ingredient")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub pid: Uuid,
    pub title: String,
    pub text: String,
    pub member_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ingredient_media_picture::Entity")]
    IngredientMediaPicture,
    #[sea_orm(has_many = "super::ingredient_media_video::Entity")]
    IngredientMediaVideo,
    #[sea_orm(
        belongs_to = "super::member::Entity",
        from = "Column::MemberId",
        to = "super::member::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Member,
}

impl Related<super::ingredient_media_picture::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientMediaPicture.def()
    }
}

impl Related<super::ingredient_media_video::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientMediaVideo.def()
    }
}

impl Related<super::member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Member.def()
    }
}

impl Related<super::media_picture::Entity> for Entity {
    fn to() -> RelationDef {
        super::ingredient_media_picture::Relation::MediaPicture.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::ingredient_media_picture::Relation::Ingredient
                .def()
                .rev(),
        )
    }
}

impl Related<super::media_video::Entity> for Entity {
    fn to() -> RelationDef {
        super::ingredient_media_video::Relation::MediaVideo.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::ingredient_media_video::Relation::Ingredient
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
